# This file was generated by GoReleaser. DO NOT EDIT.
class Licenser < Formula
  desc "Verify and append licenses to your GitHub repositories"
  homepage "https://github.com/liamawhite/licenser"
  version "0.2.1"

  if OS.mac?
    url "https://github.com/liamawhite/licenser/releases/download/v0.2.1/licenser_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "b92c225d92b09e764c9410ff9f694823cd5115cd8928b3bea3073d7697fdcd0b"
  elsif OS.linux?
    url "https://github.com/liamawhite/licenser/releases/download/v0.2.1/licenser_0.2.1_Linux_x86_64.tar.gz"
    sha256 "b6396aef9fbe9fa729c173814849d9e54bea5d8a02d61a8f1d232cc47f85df70"
  end

  def install
    bin.install "licenser"
  end

  test do
    system "#{bin}/licenser -v"
  end
end
