# This file was generated by GoReleaser. DO NOT EDIT.
class Licenser < Formula
  desc "Verify and append licenses to your GitHub repositories"
  homepage "https://github.com/liamawhite/licenser"
  version "0.5.0"

  if OS.mac?
    url "https://github.com/liamawhite/licenser/releases/download/v0.5.0/licenser_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "b21f309d5de3b3bb5738822199c311b805efdf55ff0a7643b69ade725c72a721"
  elsif OS.linux?
    url "https://github.com/liamawhite/licenser/releases/download/v0.5.0/licenser_0.5.0_Linux_x86_64.tar.gz"
    sha256 "46ee392723e53dd2bda4496c36c36430ffb4156133c0ea33a1f144f7890becde"
  end

  def install
    bin.install "licenser"
  end

  test do
    system "#{bin}/licenser -v"
  end
end
